default: &default
  pool: 5
  encoding: utf8
  timeout: 5000

hayashi: &hayashi
  <<: *default
  url: <%= ENV["HAYASHI_DATABASE_URL"] %>

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

test:
  <<: *default
  adapter: postgresql
  database: hayashi-api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
