default: &default
  pool: 5
  encoding: utf8
  timeout: 5000
  url: <%= ENV["DATABASE_URL"] %>

stellar_core:
  <<: *default
  url: <%= ENV["HAYASHI_DATABASE_URL"] %>

default_env:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
